apiVersion: v1
kind: Service
metadata:
  name: monitoring-rest-api
  namespace: monitoring
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
  selector:
    app: monitoring-rest-api
  type: ClusterIP