apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: monitoring
  name: monitoring
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: monitoring
  template:
    metadata:
      labels:
        app: monitoring
    spec:
      containers:
      - name: monitoring
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        resources:
          requests:
            cpu: "{{ .Values.resources.cpu }}"
            memory: "{{ .Values.resources.memory }}"
          limits:
            cpu: "{{ .Values.resources.cpu }}"
            memory: "{{ .Values.resources.memory }}"
        volumeMounts:
        - name: secrets
          mountPath: /app/secrets
          readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: "{{ .Values.secret.secretName }}"